sudo: required
dist: trusty
language: python
services:
- docker
env:
  global:
  - IMAGE_NAME=minikubectl
  - secure: "RJlFWHq/VG2C8KgMXTISaOJD1EK0/24bnoGJZt9cvbCoWeawPB2+zuznlDVReNHGx5DO7/Rlj+b7T2lzIeKKCe3bQzcfVOh490pVV2w+EBBAzB811V15HJb5sPZqGmJAAY3toOTAKXdW2Jd742k+fG0M5S70jHXIomw6p+Gk6D1sZoDmSxdvswnDsye5R5HeNsPQxKLPA8LftGlkpdiO+Ml75ICuXZFSMJAWfMaQ0ZMMyJH4ygWuKfyeIWzhoddBrXognaxK8Np+xk+L48Nid7kpD0G+7AKjg/MpC5bQq7mxDmKREhlnXsvSA1wiXG6LIzQSc/x9pIjJgHV9HKN49YSCqS9BMbD1a8IBOWBOTDS2uI9c7TBYQ/9IRF/u3hZ2tP+LbmzsjIg9HjJiC3vfOKYLGsTzUTf6r+2wK6MAno951Fb3+FfJi3OoOQ7W6b9RTK0t3sC5Ffa07FPssaeIXVL+BMkEYTbiTDXJxX66XNhZ2jHqhqNCbzfNdYumEnjpEeRm3XiQYxlLPPLlug7uF0XV+M3w9TvZlBci/rqSod7/uGxEmVHVpsMsTwx4U3ci6DJZ8gOnI0wxe30hNWMjDlXeWaViiUPATP/8Y3RRH28Qg4ssxKI8VPZExb7R2r+hWAFupFjat+DtkszYqXoI9qQ2U/19Ba7dLY9enYPGDh8="
  - secure: "TvRSIiZKjoVOFltHgfdOW0nDeECimzxc7EpeYb/E7GgwoNJOPX224E/Ux637IcE2pzN1gh/M2Ip03cVa1ytFxomg6rhtnPL88v6vj/9ytS7IIpoUx0cdrObLaDRlYsqoM81StylUjL4guPSlCc8aenzrYqri1tSh5/1o5OQaOifEU6iFQ77jTWTfeBwvqysjJjouEh9PWRfexhErn2ipN5DBzqTl4JUgeS9pmuQorzp2qnEgjbLk7SEZGq+RV59G7+bb/CVzqojls5ZBweHqGnrHv3lbmIEkrmVUeUDbYxoy5NsouQ9A/nvJ7fd9DZEHOXz5ngPFV9c3GxyicMBlOs1gcUmw1k0WeIypA7aMElhnxusCJwvE52fBw0JfEJf9BZkbv52pTVHSyOLLvavvV5fhIFOTBbfQINcoVLCe3Y8A2lHjB9Q8XtXU/lrjSRW6QNl399m8sNYGjnMIBSUQn/Z+pYPKg/CNXDSezvo8/l3ZCPMAEFJodhBzF4zluKA20MEAkQ2bN3KQHbm5Q5tbqWamQ7TzmjbXgCqpzLGRV4BHNEqLDJZqpmnHfA+D8HS7PFt24o//qIXSUq0lzm2EK1nKst71IH90be0K/XOudCjY2hwkpEobC7S3LEyyZNPmvnaO526wqhV53x/z3zCOLF2iRml6SF1FWYDslAVQsDQ="
script:
- "./build.sh"
